name: MergeTest
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: File Managment
        run: | 
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git rm -r README.md
          git rm -r .github
          git commit -m "Remove things"

      - name: Add Gamemode 4 datapacks
        run: |
          git remote add upstream "https://github.com/Gamemode4Dev/GM4_Datapacks.git"
          git fetch upstream
          git checkout -b gm4 upstream/master

      - name: Merge
        run: |
          git merge main --allow-unrelated-histories

      
      - name: More File Managment
        run: | 
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git rm -r README.md
          git rm -r .github
          git commit -m "Remove more things"

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: testing
          force: true